version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Lucio12345
      MYSQL_DATABASE: todolist
      MYSQL_USER: root
      MYSQL_PASSWORD: Lucio12345
    ports:
      - "3308:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql